# Generated by Django 2.1.7 on 2019-04-10 02:12

from django.db import migrations, models
import django.db.models.deletion
import helps_student.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('session_ID', models.IntegerField(primary_key=True, serialize=False)),
                ('location', models.CharField(max_length=30)),
                ('session_time', models.DateTimeField()),
                ('has_finished', models.BooleanField()),
                ('no_show', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='StaffAccount',
            fields=[
                ('staff_id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('session_history', helps_student.models.SessionListField()),
                ('faculty', models.CharField(max_length=30)),
                ('course', models.CharField(max_length=30)),
                ('preferred_first_name', models.CharField(max_length=64)),
                ('phone', models.IntegerField()),
                ('mobile', models.IntegerField()),
                ('best_contact_no', models.IntegerField()),
                ('DOB', models.DateField()),
                ('gender', models.CharField(max_length=24)),
                ('degree', models.CharField(max_length=64)),
                ('status', models.CharField(max_length=64)),
                ('first_language', models.CharField(max_length=32)),
                ('country_of_origin', models.CharField(max_length=64)),
                ('educational_background', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='StudentAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.IntegerField()),
                ('first_name', models.CharField(max_length=32)),
                ('last_name', models.CharField(max_length=32)),
                ('email', models.EmailField(max_length=254)),
                ('session_history', helps_student.models.SessionListField()),
                ('no_show_history', helps_student.models.SessionListField()),
                ('faculty', models.CharField(max_length=32)),
                ('course', models.CharField(max_length=64)),
                ('preferred_first_name', models.CharField(max_length=64)),
                ('phone', models.IntegerField()),
                ('mobile', models.IntegerField()),
                ('best_contact_no', models.IntegerField()),
                ('DOB', models.EmailField(max_length=254)),
                ('gender', models.CharField(max_length=32)),
                ('degree', models.CharField(max_length=64)),
                ('status', models.CharField(max_length=64)),
                ('first_language', models.CharField(max_length=32)),
                ('country_of_origin', models.CharField(max_length=30)),
                ('educational_background', models.CharField(max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name='session',
            name='staff_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='helps_student.StaffAccount'),
        ),
        migrations.AddField(
            model_name='session',
            name='student_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='helps_student.StudentAccount'),
        ),
    ]
