# Generated by Django 2.1.7 on 2019-04-12 06:45

from django.db import migrations, models
import django.db.models.deletion
import helps_student.models


class Migration(migrations.Migration):

    dependencies = [
        ('helps_student', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Workshop',
            fields=[
                ('workshop_ID', models.IntegerField(primary_key=True, serialize=False)),
                ('max_students', models.PositiveIntegerField()),
                ('skill_set_name', models.CharField(max_length=64)),
                ('start_dates', helps_student.models.DateListField()),
                ('end_dates', helps_student.models.DateListField()),
                ('room', models.CharField(max_length=32)),
            ],
        ),
        migrations.RenameField(
            model_name='session',
            old_name='staff_id',
            new_name='staff',
        ),
        migrations.RenameField(
            model_name='session',
            old_name='student_id',
            new_name='student',
        ),
        migrations.RemoveField(
            model_name='studentaccount',
            name='id',
        ),
        migrations.AlterField(
            model_name='staffaccount',
            name='best_contact_no',
            field=models.CharField(max_length=12),
        ),
        migrations.AlterField(
            model_name='staffaccount',
            name='mobile',
            field=models.CharField(max_length=12),
        ),
        migrations.AlterField(
            model_name='staffaccount',
            name='phone',
            field=models.CharField(max_length=12),
        ),
        migrations.AlterField(
            model_name='studentaccount',
            name='best_contact_no',
            field=models.CharField(max_length=12),
        ),
        migrations.AlterField(
            model_name='studentaccount',
            name='mobile',
            field=models.CharField(max_length=12),
        ),
        migrations.AlterField(
            model_name='studentaccount',
            name='phone',
            field=models.CharField(max_length=12),
        ),
        migrations.AlterField(
            model_name='studentaccount',
            name='student_id',
            field=models.PositiveIntegerField(primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='workshop',
            name='staff',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='helps_student.StaffAccount'),
        ),
        migrations.AddField(
            model_name='workshop',
            name='students',
            field=models.ManyToManyField(to='helps_student.StudentAccount'),
        ),
    ]
