# Generated by Django 2.1.7 on 2019-04-19 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helps_student', '0002_auto_20190412_1645'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='session_ID',
            field=models.CharField(max_length=8, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='staffaccount',
            name='staff_id',
            field=models.CharField(max_length=8, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='studentaccount',
            name='DOB',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='studentaccount',
            name='student_id',
            field=models.CharField(max_length=8, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='workshop',
            name='workshop_ID',
            field=models.CharField(max_length=8, primary_key=True, serialize=False),
        ),
    ]
