# Generated by Django 2.1.7 on 2019-05-21 02:45

import datetime
from django.db import migrations, models
import helps_student.models


class Migration(migrations.Migration):

    dependencies = [
        ('helps_student', '0003_auto_20190419_1821'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='session',
            name='session_time',
        ),
        migrations.AddField(
            model_name='session',
            name='date',
            field=models.DateField(default=datetime.datetime(2019, 5, 21, 12, 45, 48, 180578)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='session',
            name='end_time',
            field=models.DateTimeField(default=helps_student.models.default_start_time),
        ),
        migrations.AddField(
            model_name='session',
            name='start_time',
            field=models.DateTimeField(default=helps_student.models.default_start_time),
        ),
    ]
