# Generated by Django 2.1.7 on 2019-05-06 11:37

from django.db import migrations, models
import django.db.models.deletion
import helps_admin.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('session_ID', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('location', models.CharField(max_length=30)),
                ('session_time', models.DateTimeField()),
                ('has_finished', models.BooleanField()),
                ('no_show', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='StaffAccount',
            fields=[
                ('staff_id', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('session_history', helps_admin.models.DateListField()),
                ('faculty', models.CharField(max_length=30)),
                ('course', models.CharField(max_length=30)),
                ('preferred_first_name', models.CharField(max_length=64)),
                ('phone', models.CharField(max_length=12)),
                ('mobile', models.CharField(max_length=12)),
                ('best_contact_no', models.CharField(max_length=12)),
                ('DOB', models.DateField()),
                ('gender', models.CharField(max_length=24)),
                ('degree', models.CharField(max_length=64)),
                ('status', models.CharField(max_length=64)),
                ('first_language', models.CharField(max_length=32)),
                ('country_of_origin', models.CharField(max_length=64)),
                ('educational_background', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='StudentAccount',
            fields=[
                ('student_id', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=32)),
                ('last_name', models.CharField(max_length=32)),
                ('email', models.EmailField(max_length=254)),
                ('session_history', helps_admin.models.DateListField()),
                ('no_show_history', helps_admin.models.DateListField()),
                ('faculty', models.CharField(max_length=32)),
                ('course', models.CharField(max_length=64)),
                ('preferred_first_name', models.CharField(max_length=64)),
                ('phone', models.CharField(max_length=12)),
                ('mobile', models.CharField(max_length=12)),
                ('best_contact_no', models.CharField(max_length=12)),
                ('DOB', models.DateField()),
                ('gender', models.CharField(max_length=32)),
                ('degree', models.CharField(max_length=64)),
                ('status', models.CharField(max_length=64)),
                ('first_language', models.CharField(max_length=32)),
                ('country_of_origin', models.CharField(max_length=30)),
                ('educational_background', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Workshop',
            fields=[
                ('workshop_ID', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('max_students', models.PositiveIntegerField()),
                ('skill_set_name', models.CharField(max_length=64)),
                ('start_dates', helps_admin.models.DateListField()),
                ('end_dates', helps_admin.models.DateListField()),
                ('room', models.CharField(max_length=32)),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='helps_admin.StaffAccount')),
                ('students', models.ManyToManyField(to='helps_admin.StudentAccount')),
            ],
        ),
        migrations.AddField(
            model_name='session',
            name='staff',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='helps_admin.StaffAccount'),
        ),
        migrations.AddField(
            model_name='session',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='helps_admin.StudentAccount'),
        ),
    ]
