# Generated by Django 2.1.7 on 2019-05-10 03:50

from django.db import migrations, models
import helps_admin.models


class Migration(migrations.Migration):

    dependencies = [
        ('helps_admin', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='session',
            old_name='session_time',
            new_name='start_time',
        ),
        migrations.AddField(
            model_name='session',
            name='end_time',
            field=models.DateTimeField(default=helps_admin.models.default_start_time),
        ),
    ]
