# Generated by Django 2.1.7 on 2019-05-10 03:54

from django.db import migrations, models
import django.db.models.fields
import helps_admin.models


class Migration(migrations.Migration):

    dependencies = [
        ('helps_admin', '0002_auto_20190510_1350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='end_time',
            field=models.DateTimeField(default=helps_admin.models.default_start_time),
        ),
    ]
