# Generated by Django 2.1.7 on 2019-05-10 03:57

from django.db import migrations, models
import helps_admin.models


class Migration(migrations.Migration):

    dependencies = [
        ('helps_admin', '0003_auto_20190510_1354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='end_time',
            field=models.DateTimeField(default=helps_admin.models.default_start_time),
        ),
        migrations.AlterField(
            model_name='session',
            name='start_time',
            field=models.DateTimeField(default=helps_admin.models.default_start_time),
        ),
    ]
