# Generated by Django 2.1.7 on 2019-05-21 02:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helps_admin', '0004_auto_20190510_1357'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='date',
            field=models.DateField(default=datetime.datetime(2019, 5, 21, 12, 30, 53, 841517)),
            preserve_default=False,
        ),
    ]
