# Generated by Django 2.1.7 on 2019-05-26 03:50

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('helps_admin', '0005_session_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='session_ID',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
