# Generated by Django 2.1.7 on 2019-06-01 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helps_admin', '0008_auto_20190601_0056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workshop',
            name='workshop_ID',
            field=models.CharField(max_length=8, primary_key=True, serialize=False),
        ),
    ]
