# Generated by Django 2.1.7 on 2019-06-01 01:16

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('helps_admin', '0009_auto_20190601_0114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workshop',
            name='workshop_ID',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
