# Generated by Django 2.1.7 on 2019-06-01 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helps_admin', '0010_auto_20190601_0116'),
    ]

    operations = [
        migrations.AddField(
            model_name='workshop',
            name='title',
            field=models.CharField(default='', max_length=20),
        ),
    ]
